In [1]:
from sklearn.datasets import load_digits
from sklearn.model_selection import KFold, StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [5]:
fold = KFold(n_splits=5)

In [6]:
list1 = [1,3,5,6,1,8,9,5,6,7,9,10]
for train, test in fold.split(list1):
    print(train, test)

[ 3  4  5  6  7  8  9 10 11] [0 1 2]
[ 0  1  2  6  7  8  9 10 11] [3 4 5]
[ 0  1  2  3  4  5  8  9 10 11] [6 7]
[ 0  1  2  3  4  5  6  7 10 11] [8 9]
[0 1 2 3 4 5 6 7 8 9] [10 11]


In [4]:
digits = load_digits()

In [5]:
fold = StratifiedKFold(n_splits=4) # for keeping the splits balanced
fold

StratifiedKFold(n_splits=4, random_state=None, shuffle=False)

In [6]:
def get_score(model,x_train, x_test, y_train, y_test ):
    model.fit(x_train, y_train)
    return model.score(x_test, y_test)

log_score = []
svm_score = []
rf_score = []

for train_index, test_index in fold.split(digits.data, digits.target):
    x_train, x_test, y_train, y_test = digits.data[train_index],digits.data[test_index],digits.target[train_index], digits.target[test_index]
    log_score.append(get_score(LogisticRegression(), x_train, x_test, y_train, y_test))
    svm_score.append(get_score(SVC(),x_train, x_test, y_train, y_test ))
    rf_score.append(get_score(RandomForestClassifier(random_state=34),x_train, x_test, y_train, y_test ))

C:\Users\Hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

In [7]:
log_score

[0.9355555555555556,
 0.9042316258351893,
 0.9487750556792873,
 0.9175946547884187]

In [8]:
svm_score

[0.9622222222222222,
 0.9665924276169265,
 0.9821826280623608,
 0.9510022271714922]

In [9]:
rf_score

[0.9377777777777778,
 0.9086859688195991,
 0.9665924276169265,
 0.9287305122494433]

In [10]:
import numpy as np
print(np.mean(log_score))
print(np.mean(svm_score))
print(np.mean(rf_score))

0.9265392229646128
0.9654998762682504
0.9354466716159366


In [11]:
from sklearn.model_selection import cross_val_score

In [12]:
log_score = cross_val_score(LogisticRegression(), X = digits.data, y = digits.target, cv=5)# default cv = 5
svm_score = cross_val_score(SVC(), X = digits.data, y = digits.target)
rf_score = cross_val_score(RandomForestClassifier(random_state=12), X = digits.data, y = digits.target)

C:\Users\Hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

In [13]:
print(log_score)
print(svm_score)
print(rf_score)

[0.92222222 0.86944444 0.94150418 0.93871866 0.89693593]
[0.96111111 0.94444444 0.98328691 0.98885794 0.93871866]
[0.93611111 0.91111111 0.95264624 0.97771588 0.9275766 ]


In [14]:
print(np.mean(log_score))
print(np.mean(svm_score))
print(np.mean(rf_score))

0.9137650882079852
0.9632838130609718
0.9410321881770349


In [15]:
log_score = cross_val_score(LogisticRegression(), X = digits.data, y = digits.target, cv=3)
svm_score = cross_val_score(SVC(), X = digits.data, y = digits.target, cv=3)
rf_score = cross_val_score(RandomForestClassifier(random_state=12), X = digits.data, y = digits.target, cv=3)

C:\Users\Hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

In [16]:
print(log_score)
print(svm_score)
print(rf_score)

[0.92153589 0.94156928 0.91652755]
[0.96494157 0.97996661 0.96494157]
[0.94156928 0.96160267 0.92988314]


In [17]:
print(np.mean(log_score))
print(np.mean(svm_score))
print(np.mean(rf_score))

0.9265442404006677
0.9699499165275459
0.9443516972732331
